version = 1

exclude_patterns = ["/dist"]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = ["nodejs"]

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "21"

[[transformers]]
name = "prettier"

[[transformers]]
name = "google-java-format"