version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-hoteldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: hoteldb
    ports:
      - "3306:3306"
    # volumes:
    #   - mysql_data:/var/lib/mysql

# volumes:
#   mysql_data:
